export enum LEVELS {
  ELEMENTARY = 'A1',
  PREINTERMEDIATE = 'A2',
  INTERMEDIATE = 'B1',
  UPPERNTERMEDIATE = 'B2',
  ADVANCED = 'C1',
  PROFICIENCY = 'C2',
}

export const GROUPS = [
  LEVELS.ELEMENTARY,
  LEVELS.PREINTERMEDIATE,
  LEVELS.INTERMEDIATE,
  LEVELS.UPPERNTERMEDIATE,
  LEVELS.ADVANCED,
  LEVELS.PROFICIENCY
];

export const PAGES = 29;
